### ISSUE TITLE
c module won't complile after updating from 3.7.3 to 4.0.1

### ISSUE THREAD

**Issue by Minami-Kotori** [cmake-js/cmake-js#155]
Hi there

I'm kinda new to C and I'm working on an Electron project. When I updated cmake-js to 5.0.1(or 4.0.1) both gave me an error when I tried rebuilding my c++ module.

`nan.h:49:3: error: This version of node/NAN/v8 requires a C++11 compiler.`

here is my cmakelist

```
cmake_minimum_required(VERSION 3.10)
project(XXX)

file(GLOB SOURCE_FILES "main.cpp")
add_library(${PROJECT_NAME} SHARED ${SOURCE_FILES})
add_subdirectory(C-Library)

set(CMAKE_CXX_STANDARD 11)

set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")

target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_JS_INC} ${HIDAPI_DIR})

target_link_libraries(${PROJECT_NAME} PUBLIC XXX ${CMAKE_JS_LIB})
```

I'm currently sticking to 3.7.3, just wondering if anyone can point me to the right direction thanks.

**Comment by Minami-Kotori** [comment]
apparently it's caused by the c library I'm using, after adding 
`set(CMAKE_C_STANDARD 11)`

it worked.
